# Generated by Django 5.2.8 on 2025-12-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaciaapp', '0002_room_roombooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='features',
            new_name='description',
        ),
    ]
