# Generated by Django 5.2.8 on 2025-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acaciaapp', '0004_room_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='reserved_name',
        ),
    ]
