# Generated by Django 5.2.8 on 2025-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acaciaapp', '0006_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
